overwrite: true
schema:
  - https://liquix-react.myshopify.com/admin/api/2022-01/graphql:
      headers:
        X-Shopify-Access-Token: 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
documents: "_server/shopify/**/*.{ts,tsx}"
generates:
  _server\shopify\types.ts:
    plugins:
      - typescript
      - typescript-operations
    config:
      onlyOperationTypes: true
      skipTypeNameForRoot: true
      skipTypename: true
      enumsAsTypes: true
